### ISSUE TITLE
Hide "Completed sync" automagically when it was successful.

### ISSUE THREAD

**Issue by TilBlechschmidt** [TexDocs/TexDocs-macOS#3]
It is rather annoying to have a popup that prevents to get to work when starting the app.

**Comment by NoahPeeters** [comment]
Fixed with [e12f7a1c10c21f81f44c3b9b3d4baa3aa03d1031](https://github.com/NoahPeeters/TexDocs/commit/e12f7a1c10c21f81f44c3b9b3d4baa3aa03d1031)
