### ISSUE TITLE
Block indentation

### ISSUE THREAD

**Issue by TilBlechschmidt** [TexDocs/TexDocs-macOS#5]
It should be possible to use Tab and Shift+Tab to indent/unindent selected code blocks.

**Comment by NoahPeeters** [comment]
I originally implemented cmd + [ and ] for this (this is the default in Xcode) and (shift-)tab to navigate tokens.
I added indent/unindent for (shift-)tab if there isn't a token to jump to in the latest commit.

**Comment by TilBlechschmidt** [comment]
It is already a step up but for it to be perfect the (un-)indentation with (shift+)TAB should only happen when an area is selected or the cursor is in front the text in the line (ignoring leading whitespaces). 

The way it is right now one is unable to insert \t characters at arbitrary positions.

**Comment by NoahPeeters** [comment]
Fixed with 4204daac5adaec4f38926d9ffeb800e510e97c02
